# Generated by Django 3.0.12 on 2021-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('hits', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
